apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chat.fullname" . }}-frontend
  labels:
    {{- include "todo-chat.labels" . | nindent 4 }}
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.app.frontend.service.port }}
      targetPort: {{ .Values.app.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "todo-chat.selectorLabels" . | nindent 4 }}
    component: frontend
