apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chat.fullname" . }}-backend
  labels:
    {{- include "todo-chat.labels" . | nindent 4 }}
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.app.backend.service.port }}
      targetPort: {{ .Values.app.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "todo-chat.selectorLabels" . | nindent 4 }}
    component: backend
