openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
  description: API for authentication and authorization in the Todo application
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /api/v1/tasks/{user_id}:
    get:
      summary: Get all tasks for an authenticated user
      parameters:
        - name: user_id
          in: path
          required: true
          description: User identifier (must match authenticated user)
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response with user's tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../001-backend-api-data-layer/contracts/task-api.yaml#/components/schemas/Task'
        '401':
          description: Unauthorized - missing or invalid token
        '403':
          description: Forbidden - user trying to access other user's tasks
  /api/v1/tasks/:
    post:
      summary: Create a new task for authenticated user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../001-backend-api-data-layer/contracts/task-api.yaml#/components/schemas/CreateTaskRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '../001-backend-api-data-layer/contracts/task-api.yaml#/components/schemas/Task'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized - missing or invalid token
  /api/v1/tasks/{task_id}:
    put:
      summary: Update a task (user must own the task)
      parameters:
        - name: task_id
          in: path
          required: true
          description: Task identifier
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../001-backend-api-data-layer/contracts/task-api.yaml#/components/schemas/UpdateTaskRequest'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '../001-backend-api-data-layer/contracts/task-api.yaml#/components/schemas/Task'
        '401':
          description: Unauthorized - missing or invalid token
        '403':
          description: Forbidden - user doesn't own the task
        '404':
          description: Task not found
    delete:
      summary: Delete a task (user must own the task)
      parameters:
        - name: task_id
          in: path
          required: true
          description: Task identifier
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized - missing or invalid token
        '403':
          description: Forbidden - user doesn't own the task
        '404':
          description: Task not found
  /api/v1/tasks/{task_id}/toggle:
    patch:
      summary: Toggle task completion status (user must own the task)
      parameters:
        - name: task_id
          in: path
          required: true
          description: Task identifier
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Task completion status toggled
          content:
            application/json:
              schema:
                $ref: '../001-backend-api-data-layer/contracts/task-api.yaml#/components/schemas/Task'
        '401':
          description: Unauthorized - missing or invalid token
        '403':
          description: Forbidden - user doesn't own the task
        '404':
          description: Task not found
  /api/v1/auth/login:
    post:
      summary: Login endpoint (public)
      description: This endpoint is public and doesn't require authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: User's email address
                password:
                  type: string
                  description: User's password
      responses:
        '200':
          description: Login successful, returns JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: JWT access token
                  token_type:
                    type: string
                    description: Type of token (usually "bearer")
        '401':
          description: Invalid credentials
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from authentication endpoints