openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
  description: API for managing user tasks in the Todo application
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /api/v1/tasks/{user_id}:
    get:
      summary: Get all tasks for a user
      parameters:
        - name: user_id
          in: path
          required: true
          description: User identifier
          schema:
            type: string
      responses:
        '200':
          description: Successful response with user's tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '404':
          description: User not found
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
  /api/v1/tasks/{task_id}:
    put:
      summary: Update a task
      parameters:
        - name: task_id
          in: path
          required: true
          description: Task identifier
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
    delete:
      summary: Delete a task
      parameters:
        - name: task_id
          in: path
          required: true
          description: Task identifier
          schema:
            type: string
      responses:
        '204':
          description: Task deleted successfully
        '404':
          description: Task not found
  /api/v1/tasks/{task_id}/toggle:
    patch:
      summary: Toggle task completion status
      parameters:
        - name: task_id
          in: path
          required: true
          description: Task identifier
          schema:
            type: string
      responses:
        '200':
          description: Task completion status toggled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - completed
        - user_id
        - created_at
      properties:
        id:
          type: string
          description: Unique task identifier
        title:
          type: string
          description: Task title
          maxLength: 255
        description:
          type: string
          description: Task description
          maxLength: 1000
        completed:
          type: boolean
          description: Completion status
          default: false
        user_id:
          type: string
          description: User identifier
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
    CreateTaskRequest:
      type: object
      required:
        - title
        - user_id
      properties:
        title:
          type: string
          maxLength: 255
        description:
          type: string
          maxLength: 1000
        user_id:
          type: string
        completed:
          type: boolean
          default: false
    UpdateTaskRequest:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
        description:
          type: string
          maxLength: 1000
        completed:
          type: boolean