openapi: 3.0.0
info:
  title: Authentication API for Todo Application
  version: 1.0.0
  description: API for handling authentication and authorization in the Todo application
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /api/v1/tasks/{user_id}:
    get:
      summary: Get all tasks for a specific user
      parameters:
        - name: user_id
          in: path
          required: true
          description: User identifier (must match authenticated user)
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response with user's tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - missing or invalid token
        '403':
          description: Forbidden - user trying to access another user's tasks
        '404':
          description: User not found (if user_id doesn't exist)
  /api/v1/tasks/:
    post:
      summary: Create a new task for authenticated user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input data
        '401':
          description: Unauthorized - missing or invalid token
  /api/v1/tasks/{task_id}:
    put:
      summary: Update a task (user must own the task)
      parameters:
        - name: task_id
          in: path
          required: true
          description: Task identifier
          schema:
            type: integer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - missing or invalid token
        '403':
          description: Forbidden - user doesn't own the task
        '404':
          description: Task not found
    delete:
      summary: Delete a task (user must own the task)
      parameters:
        - name: task_id
          in: path
          required: true
          description: Task identifier
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized - missing or invalid token
        '403':
          description: Forbidden - user doesn't own the task
        '404':
          description: Task not found
  /api/v1/tasks/{task_id}/toggle:
    patch:
      summary: Toggle task completion status (user must own the task)
      parameters:
        - name: task_id
          in: path
          required: true
          description: Task identifier
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Task completion status toggled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - missing or invalid token
        '403':
          description: Forbidden - user doesn't own the task
        '404':
          description: Task not found
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained through authentication
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - completed
        - user_id
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          description: Unique task identifier
        title:
          type: string
          description: Task title
          maxLength: 255
        description:
          type: string
          description: Task description
          maxLength: 1000
        completed:
          type: boolean
          description: Task completion status
          default: false
        user_id:
          type: string
          description: User identifier (foreign key)
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
    TaskCreate:
      type: object
      required:
        - title
        - user_id
      properties:
        title:
          type: string
          description: Task title
          maxLength: 255
        description:
          type: string
          description: Task description
          maxLength: 1000
        completed:
          type: boolean
          description: Task completion status
          default: false
        user_id:
          type: string
          description: User identifier (will be overridden with authenticated user ID)
    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          description: Updated task title
          maxLength: 255
        description:
          type: string
          description: Updated task description
          maxLength: 1000
        completed:
          type: boolean
          description: Updated task completion status